version: "3.7"
services:

#  tracardi:
#    build: .
##    image: tracardi-event-server
#    environment:
#      ELASTIC_HOST: http://elasticsearch:9200
#    ports:
#      - 8484:80

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.13.1
    volumes: # Persist ES data in seperate "esdata" volume
      - esdata1:/usr/share/elasticsearch/data
    environment:
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - discovery.type=single-node
      - xpack.security.enabled=false
      - cluster.name=contextElasticSearch
    ports: # Expose Elasticsearch ports
      - 9300:9300
      - 9200:9200

  kibana:
    image: docker.elastic.co/kibana/kibana:7.13.1
    hostname: kibana
    ports:
      - 5601:5601
    environment:
      ELASTICSEARCH_URL: http://elasticsearch:9200
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200

volumes: # Define seperate volume for Elasticsearch data
  esdata1:
    driver: local