name: Greetings

on: [pull_request, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: 'Thank you for spotting this issue. We will take care of it as soon as possible. Please star and watch our project in order to get informed on the progress.'
        pr-message: 'Thank you for your pull request. Please start and watch our project in order to get informed on the progress.'
